/**
 * CI → objective feedback bridge — DROPLET-SIDE POLLER (obj 701617).
 *
 * WHAT THE OPERATOR ASKED: "Is there a way we can push test results back to the objective
 * that kicked off the PR so it will keep iterating until it is passing?" — yes. When
 * an example-platform PR's `vitest` check fails, post a concise failing-test summary into
 * the originating Command Center objective (via the LOCAL internal API) so the worker
 * session re-opens and iterates until the check goes green.
 *
 * WHY A POLLER (not a webhook, not a self-hosted runner):
 *  - The Command Center internal API (POST /objectives/:id/message) is LOCALHOST-ONLY,
 *    no-auth, droplet-local. GitHub-HOSTED runners cannot reach it, so the bridge MUST
 *    run on the droplet.
 *  - This is a PULL loop: it is READ-ONLY against GitHub (`gh pr list/checks/run view`)
 *    and POSTs only to localhost. It does NOT require a public webhook endpoint, an
 *    inbound tunnel, or any GitHub org/repo settings change, and it never executes
 *    untrusted PR code (a self-hosted runner would — that path is deferred to Operator).
 *  - A webhook-driven sibling already exists (services/external-remediation.ts, obj
 *    1960) but depends on GitHub → droplet delivery. This poller is the pull-based
 *    complement and SHARES the same dedupe table (`external_check_remediations`) so the
 *    two can never double-nudge the same failing commit.
 *
 * SAFETY INVARIANTS:
 *  - Ships DARK: the act-path is gated by CI_FEEDBACK_BRIDGE_ENABLED (env) OR
 *    settings.ci_feedback_bridge_enabled (default '0'). With the flag OFF the loop only
 *    logs "WOULD nudge" and posts nothing — enabling it is an explicit owner decision.
 *  - Loop guard: dedupe by (repo, pr, check, head_sha) via INSERT OR IGNORE on the
 *    shared UNIQUE table, so the SAME failing commit is nudged at most once; PLUS a
 *    per-PR attempt cap (MAX_CI_BRIDGE_NUDGES, default 5). On cap exhaustion it marks
 *    the objective has_blockers ONCE and stops — never an infinite loop.
 *  - objid extraction is safe: no id derivable from branch (`worker/<id>-…`) or title
 *    (`obj <id>`) ⇒ SKIP + log, never guess.
 *  - Crash-safe: one bad PR never aborts the pass; the pass never throws to the caller.
 *  - No secrets: reuses the droplet's existing `gh` auth (GH_CONFIG_DIR=/etc/gh). No
 *    tokens are read, logged, or committed.
 */
import { execFile } from 'child_process'
import { getDb } from '../db/index.js'
import type { Database } from 'better-sqlite3'
import { classifyCheckFixability } from './external-remediation-classify.js'

// ── Config ──────────────────────────────────────────────────────────────────────
/** Repo to poll. Overridable for tests / other repos. */
const DEFAULT_REPO = process.env.CI_FEEDBACK_BRIDGE_REPO || 'your-org/example-platform'
/** The check whose failure triggers a nudge. Matched case-insensitively as a substring
 *  so "vitest (app suite)" matches "vitest". */
const VITEST_CHECK_MATCH = 'vitest'
/** How often the scheduler runs a pass. */
const TICK_MS = 5 * 60 * 1000
const PORT = parseInt(process.env.PORT || '3002', 10)
/** Token-discipline caps on the failing-test summary. */
const MAX_SUMMARY_LINES = 60
const MAX_SUMMARY_CHARS = 4000

/** Per-PR nudge cap. Bounds cost / prevents infinite loops. Env-overridable. */
export function maxCiBridgeNudges(env: NodeJS.ProcessEnv = process.env): number {
  const raw = parseInt(env.MAX_CI_BRIDGE_NUDGES || '', 10)
  return Number.isInteger(raw) && raw > 0 ? raw : 5
}

/** Owner switch. env CI_FEEDBACK_BRIDGE_ENABLED (truthy wins) OR
 *  settings.ci_feedback_bridge_enabled === '1'. Default OFF. Read at call time so
 *  flipping it arms/disarms with no restart. */
export function isCiBridgeEnabled(env: NodeJS.ProcessEnv = process.env, db?: Database): boolean {
  const v = (env.CI_FEEDBACK_BRIDGE_ENABLED || '').trim().toLowerCase()
  if (v === '1' || v === 'true' || v === 'yes' || v === 'on') return true
  try {
    const row = (db || getDb())
      .prepare(`SELECT value FROM settings WHERE key = 'ci_feedback_bridge_enabled'`)
      .get() as { value: string } | undefined
    return row?.value === '1'
  } catch {
    return false
  }
}

// ── objid extraction (pure, exhaustively testable) ──────────────────────────────
/**
 * Derive the originating CC objective id from a PR's head branch and/or title.
 *  - branch: `worker/<id>-slug` (the canonical CC worker branch shape).
 *  - title:  `... (obj <id>)` / `obj <id>` / `objective #<id>` (case-insensitive).
 * Branch wins when both are present and agree; if they disagree we trust the BRANCH
 * (it is machine-generated by the server; the title is human/LLM-authored). Returns
 * null when NOTHING matches — the caller SKIPS (never guesses).
 */
export function extractObjectiveId(branch: string | null | undefined, title: string | null | undefined): number | null {
  const fromBranch = (() => {
    const m = /^worker\/(\d+)-/.exec((branch || '').trim())
    return m ? parseInt(m[1], 10) : null
  })()
  const fromTitle = (() => {
    const m = /\bobj(?:ective)?\s*#?\s*(\d+)/i.exec(title || '')
    return m ? parseInt(m[1], 10) : null
  })()
  const id = fromBranch ?? fromTitle
  return Number.isInteger(id) && (id as number) > 0 ? (id as number) : null
}

// ── vitest failure summary extraction (pure, testable) ──────────────────────────
// Strip ANSI colour codes. `gh run view --log-failed` in a non-TTY pipe encodes the
// ESC byte as the LITERAL two-char caret sequence `^[` (0x5e 0x5b), NOT the 0x1b control
// byte — so we match BOTH forms. Also drop the `⎯` box-drawing decoration vitest wraps
// around its "Failed Tests N" banner, and any orphan trailing `^[`.
const ANSI_RE = /(?:\x1b|\^\[)\[[0-9;]*[A-Za-z]/g
const DECORATION_RE = /[⎯─]{2,}/g
/** `gh run view --log-failed` prefixes every line with `<job>\t<step>\t<ISO ts> `.
 *  Strip that so the summary reads like local vitest output. */
const GH_LOG_PREFIX_RE = /^[^\t]*\t[^\t]*\t\d{4}-\d{2}-\d{2}T[0-9:.]+Z\s?/
/** Lines worth keeping from a vitest failure — the actionable skeleton, not the whole
 *  log: the "Failed Tests N" banner, each `FAIL <file> > <test>`, each `× <test>`
 *  bullet, and the `Test Files` / `Tests` summary counts. */
const KEEP_RE = /(Failed Tests\s+\d+|^\s*FAIL\s|^\s*[×✗]\s|Test Files\s+\d+|^\s*Tests\s+\d+|Duration\s)/

/**
 * Reduce a raw `gh run view --log-failed` dump to a concise, actionable failing-test
 * summary. Strips ANSI + the gh log prefix, keeps only the failure skeleton, dedupes,
 * and clips to the token-discipline caps. Returns '' when nothing matched (caller
 * falls back to a generic "vitest failed" message).
 */
export function extractVitestFailureSummary(rawLog: string): string {
  if (!rawLog) return ''
  const seen = new Set<string>()
  const kept: string[] = []
  for (const rawLine of rawLog.split('\n')) {
    const line = rawLine
      .replace(ANSI_RE, '')
      .replace(GH_LOG_PREFIX_RE, '')
      .replace(DECORATION_RE, '')
      .replace(/\^\[/g, '') // orphan caret-ESC with no trailing code
      .replace(/\s+$/, '')
    if (!line) continue
    if (!KEEP_RE.test(line)) continue
    const norm = line.trim()
    if (seen.has(norm)) continue
    seen.add(norm)
    kept.push(line)
    if (kept.length >= MAX_SUMMARY_LINES) break
  }
  let out = kept.join('\n')
  if (out.length > MAX_SUMMARY_CHARS) out = out.slice(0, MAX_SUMMARY_CHARS) + '\n… (trimmed for token discipline) …'
  return out
}

/** Extract the GitHub Actions run id from a check's job link, e.g.
 *  https://github.com/OWNER/REPO/actions/runs/<runId>/job/<jobId>. */
export function extractRunId(link: string | null | undefined): number | null {
  const m = /\/actions\/runs\/(\d+)/.exec(link || '')
  return m ? parseInt(m[1], 10) : null
}

// ── gh exec (DI for tests) ──────────────────────────────────────────────────────
/** The server's `gh` has no auth in its default config dir; the host hosts.yml is
 *  mounted at /etc/gh. Mirrors external-remediation.ghExecEnv. */
function ghExecEnv(base: NodeJS.ProcessEnv = process.env): NodeJS.ProcessEnv {
  return { ...base, GH_CONFIG_DIR: base.GH_CONFIG_DIR || '/etc/gh' }
}
export type ExecFn = (file: string, args: string[]) => Promise<string>
const defaultExec: ExecFn = (file, args) =>
  new Promise((resolve, reject) => {
    execFile(file, args, { timeout: 60000, maxBuffer: 20 * 1024 * 1024, env: ghExecEnv() }, (err, stdout, stderr) => {
      // For `gh run view --log-failed`, gh exits non-zero when the run failed even
      // though stdout holds the log we want — so return stdout if we have it.
      if (stdout && stdout.length > 0) resolve(stdout.toString())
      else if (err) reject(new Error((stderr || err.message || '').toString().slice(0, 500)))
      else resolve((stdout || '').toString())
    })
  })

/** POST the summary to the localhost internal message endpoint (DI for tests). */
export type PostMessageFn = (objectiveId: number, message: string) => Promise<{ ok: boolean; status: number; body: string }>
const defaultPostMessage: PostMessageFn = async (objectiveId, message) => {
  const res = await fetch(`http://localhost:${PORT}/api/internal/objectives/${objectiveId}/message`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ message }),
  })
  const body = await res.text().catch(() => '')
  return { ok: res.ok, status: res.status, body }
}

// ── Types ───────────────────────────────────────────────────────────────────────
interface PrRow { number: number; title: string; headRefName: string; headRefOid: string }
interface CheckRow { name: string; state: string; link: string; workflow?: string }

export interface CiBridgeDeps {
  db?: Database
  exec?: ExecFn
  postMessage?: PostMessageFn
  env?: NodeJS.ProcessEnv
  repo?: string
  /** When true, bypass the enable gate (used by the one-shot demo/CLI runner). */
  force?: boolean
}

export interface PrOutcome {
  pr: number
  objectiveId: number | null
  action: 'no-objid' | 'no-vitest-check' | 'vitest-pass' | 'duplicate' | 'cap-exhausted' | 'nudged' | 'disabled-dry-run' | 'post-failed' | 'not-code-fixable' | 'error'
  detail?: string
}

// ── Build the nudge message ──────────────────────────────────────────────────────
export function buildNudgeMessage(args: { pr: number; repo: string; headSha: string; checkName: string; link: string; summary: string; attempt: number; cap: number }): string {
  const { pr, repo, headSha, checkName, link, summary, attempt, cap } = args
  return [
    `## ⚠️ CI test failure on your PR — auto-iterate (attempt ${attempt}/${cap})`,
    ``,
    `The \`${checkName}\` check just FAILED on PR #${pr} (${repo}) for this objective.`,
    `This is an automated hand-off from the CI→objective feedback bridge. Diagnose the`,
    `failing tests below, fix them in your worktree, push, and confirm the check goes green.`,
    ``,
    `- Commit: \`${headSha || '(unknown)'}\``,
    `- Check run: ${link || '(no link)'}`,
    ``,
    summary
      ? `**Failing tests (only the failing lines were captured — token discipline):**\n\`\`\`\n${summary}\n\`\`\``
      : `(Could not extract the failing-test lines — open the check run link above.)`,
    ``,
    `Fix in your PR-branch worktree (absolute paths only), commit, and \`git push\`. Do NOT`,
    `merge — Operator merges. If it fails again you'll get another automated nudge (bounded at ${cap}).`,
  ].join('\n')
}

// ── Orchestration ────────────────────────────────────────────────────────────────
/**
 * Run ONE polling pass over the repo's open PRs. Returns a per-PR outcome list for
 * logging/tests. Never throws.
 */
export async function runCiFeedbackBridgeOnce(deps: CiBridgeDeps = {}): Promise<PrOutcome[]> {
  const db = deps.db || getDb()
  const exec = deps.exec || defaultExec
  const postMessage = deps.postMessage || defaultPostMessage
  const env = deps.env || process.env
  const repo = deps.repo || DEFAULT_REPO
  const cap = maxCiBridgeNudges(env)
  const enabled = deps.force || isCiBridgeEnabled(env, db)
  const outcomes: PrOutcome[] = []

  let prs: PrRow[]
  try {
    const raw = await exec('gh', ['pr', 'list', '--repo', repo, '--state', 'open', '--json', 'number,title,headRefName,headRefOid', '--limit', '50'])
    prs = JSON.parse(raw) as PrRow[]
  } catch (err) {
    console.error(`[ci-feedback-bridge] gh pr list failed for ${repo}:`, (err as Error).message)
    return outcomes
  }

  for (const pr of prs) {
    try {
      const objectiveId = extractObjectiveId(pr.headRefName, pr.title)
      if (!objectiveId) {
        console.log(`[ci-feedback-bridge] PR #${pr.number}: no objective id in branch "${pr.headRefName}" / title — SKIP`)
        outcomes.push({ pr: pr.number, objectiveId: null, action: 'no-objid' })
        continue
      }

      // Read this PR's checks; find the vitest one.
      let checks: CheckRow[]
      try {
        const raw = await exec('gh', ['pr', 'checks', String(pr.number), '--repo', repo, '--json', 'name,state,link,workflow'])
        checks = JSON.parse(raw) as CheckRow[]
      } catch (err) {
        // `gh pr checks` exits non-zero when any check is failing but still prints JSON
        // to stdout — defaultExec returns that stdout, so a throw here means no checks yet.
        console.log(`[ci-feedback-bridge] PR #${pr.number}: could not read checks (${(err as Error).message}) — SKIP`)
        outcomes.push({ pr: pr.number, objectiveId, action: 'no-vitest-check', detail: 'checks unreadable' })
        continue
      }
      const vitest = checks.find(c => (c.name || '').toLowerCase().includes(VITEST_CHECK_MATCH))
      if (!vitest) {
        outcomes.push({ pr: pr.number, objectiveId, action: 'no-vitest-check' })
        continue
      }
      // Fixability gate (obj 704698, gap A) — the two engines share the dedupe table, so
      // they must share the classifier too: a check an operator has reclassified as
      // environmental/advisory/scheduled must not be nudged by the poller after the
      // webhook loop correctly declined it.
      const fixability = classifyCheckFixability(vitest.name, { env, db })
      if (!fixability.fixable) {
        console.log(`[ci-feedback-bridge] PR #${pr.number}: check "${vitest.name}" is ${fixability.class}, not code-fixable — SKIP`)
        outcomes.push({ pr: pr.number, objectiveId, action: 'not-code-fixable', detail: fixability.class })
        continue
      }
      const state = (vitest.state || '').toUpperCase()
      if (state !== 'FAILURE' && state !== 'ERROR') {
        // PASS / PENDING / SKIPPED → no-op. We only act on a definitive failure.
        outcomes.push({ pr: pr.number, objectiveId, action: 'vitest-pass', detail: state })
        continue
      }

      // ── Loop guard: dedupe by (repo, pr, check, head_sha) on the SHARED table so the
      // webhook engine and this poller can't both nudge the same commit. ──
      const attemptBefore = countBridgeNudges(db, repo, pr.number)
      const attempt = attemptBefore + 1
      const ins = db.prepare(
        `INSERT OR IGNORE INTO external_check_remediations
           (objective_id, repo, pr_number, check_name, head_sha, attempt, check_class)
         VALUES (?, ?, ?, ?, ?, ?, 'code-fixable')`,
      ).run(objectiveId, repo, pr.number, vitest.name, pr.headRefOid, attempt)
      if (ins.changes === 0) {
        outcomes.push({ pr: pr.number, objectiveId, action: 'duplicate', detail: pr.headRefOid.slice(0, 8) })
        continue
      }

      // ── Cap: once exceeded, escalate ONCE (has_blockers) and stop. ──
      if (attempt > cap) {
        const alreadyEscalated = countEscalated(db, repo, pr.number) > 0
        if (!alreadyEscalated) {
          escalate(db, objectiveId, pr.number, vitest.name, cap)
          db.prepare(
            `UPDATE external_check_remediations SET escalated = 1 WHERE repo = ? AND pr_number = ? AND check_name = ? AND head_sha = ?`,
          ).run(repo, pr.number, vitest.name, pr.headRefOid)
        }
        outcomes.push({ pr: pr.number, objectiveId, action: 'cap-exhausted', detail: `attempt ${attempt}/${cap}` })
        continue
      }

      // ── Fetch ONLY failing lines and summarize. ──
      let summary = ''
      const runId = extractRunId(vitest.link)
      if (runId) {
        try {
          const rawLog = await exec('gh', ['run', 'view', String(runId), '--repo', repo, '--log-failed'])
          summary = extractVitestFailureSummary(rawLog)
        } catch (err) {
          console.warn(`[ci-feedback-bridge] PR #${pr.number}: log fetch failed (${(err as Error).message}) — nudging with link only`)
        }
      }

      const message = buildNudgeMessage({ pr: pr.number, repo, headSha: pr.headRefOid, checkName: vitest.name, link: vitest.link, summary, attempt, cap })

      // SHIP DARK: with the flag off, log intent and post nothing.
      if (!enabled) {
        console.log(`[ci-feedback-bridge] DARK — WOULD nudge obj ${objectiveId} (PR #${pr.number}, ${vitest.name} FAIL, attempt ${attempt}/${cap})`)
        // Roll back the dedupe row so a real (enabled) pass still fires for this SHA.
        db.prepare(`DELETE FROM external_check_remediations WHERE repo = ? AND pr_number = ? AND check_name = ? AND head_sha = ?`)
          .run(repo, pr.number, vitest.name, pr.headRefOid)
        outcomes.push({ pr: pr.number, objectiveId, action: 'disabled-dry-run', detail: `attempt ${attempt}/${cap}` })
        continue
      }

      const resp = await postMessage(objectiveId, message)
      if (!resp.ok) {
        console.error(`[ci-feedback-bridge] POST /message failed for obj ${objectiveId} (PR #${pr.number}): ${resp.status} ${resp.body.slice(0, 200)}`)
        outcomes.push({ pr: pr.number, objectiveId, action: 'post-failed', detail: `${resp.status}` })
        continue
      }
      console.log(`[ci-feedback-bridge] nudged obj ${objectiveId} — PR #${pr.number} ${vitest.name} FAIL (attempt ${attempt}/${cap})`)
      outcomes.push({ pr: pr.number, objectiveId, action: 'nudged', detail: `attempt ${attempt}/${cap}` })
    } catch (err) {
      console.error(`[ci-feedback-bridge] PR #${pr.number} handling error:`, (err as Error).message)
      outcomes.push({ pr: pr.number, objectiveId: null, action: 'error', detail: (err as Error).message })
    }
  }
  return outcomes
}

function countBridgeNudges(db: Database, repo: string, pr: number): number {
  const row = db.prepare('SELECT COUNT(*) AS n FROM external_check_remediations WHERE repo = ? AND pr_number = ?').get(repo, pr) as { n: number }
  return row?.n || 0
}
function countEscalated(db: Database, repo: string, pr: number): number {
  const row = db.prepare('SELECT COUNT(*) AS n FROM external_check_remediations WHERE repo = ? AND pr_number = ? AND escalated = 1').get(repo, pr) as { n: number }
  return row?.n || 0
}
function escalate(db: Database, objectiveId: number, pr: number, checkName: string, cap: number): void {
  const note = `CI feedback bridge hit its ${cap}-nudge cap on "${checkName}" (PR #${pr}). Needs a human — the loop has stopped and will not retry.`
  try {
    db.prepare("UPDATE objectives SET has_blockers = 1, updated_at = datetime('now') WHERE id = ?").run(objectiveId)
  } catch (err) {
    console.warn('[ci-feedback-bridge] escalate failed:', (err as Error).message)
  }
  console.warn(`[ci-feedback-bridge] ESCALATED obj ${objectiveId} PR #${pr}: ${note}`)
}

// ── Scheduler ────────────────────────────────────────────────────────────────────
let tickTimer: ReturnType<typeof setInterval> | null = null

/**
 * Start the CI→objective feedback bridge poller (5-min tick).
 *
 * The TIMER always arms (so flipping settings.ci_feedback_bridge_enabled to '1' takes
 * effect with no restart), but each pass is INERT while the flag is OFF: it logs
 * "WOULD nudge" and posts nothing. Enabling it is an explicit owner decision because it
 * starts messaging live workers. Fully disable the timer with
 * CI_FEEDBACK_BRIDGE_DISABLED=true.
 */
export function startCiFeedbackBridge(): void {
  if (process.env.CI_FEEDBACK_BRIDGE_DISABLED === 'true') {
    console.log('[ci-feedback-bridge] Poller disabled via CI_FEEDBACK_BRIDGE_DISABLED=true')
    return
  }
  if (tickTimer) return
  tickTimer = setInterval(() => {
    if (!isCiBridgeEnabled()) return // cheap gate — skip the gh calls entirely while dark
    runCiFeedbackBridgeOnce()
      .then(outs => {
        const nudged = outs.filter(o => o.action === 'nudged').length
        if (nudged > 0) console.log(`[ci-feedback-bridge] pass complete — ${nudged} nudge(s) sent`)
      })
      .catch(err => console.error('[ci-feedback-bridge] pass failed:', err))
  }, TICK_MS)
  console.log('[ci-feedback-bridge] Poller started — 5-min tick (INERT until ci_feedback_bridge_enabled=1)')
}
